export default { //when using the common a style of importing and exporting content in JS files
    products: [ // Create properties of products
        {
            //create ID is suitable for MongoDB 
            _id: '111111111111111111111111',
            name: 'Air Force 1 Low 07 LV8 Panda Shoes',
            category: 'Shoes',
            image: '/images/product-1.jpg',
            price: 39,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 216,
            countInStock: 6,
        },
        {
            _id: '222222222222222222222222',
            name: 'NY 90 Core White FZ2247 Shoes',
            category: 'Shoes',
            image: '/images/product-2.jpg',
            price: 85.9,
            brand: 'Adidas',
            rating: 4,
            numReviews: 50,
            countInStock: 5,
        },
        {
            _id: '333333333333333333333333',
            name: 'Samba OG IE3675 Shoes',
            category: 'Shoes',
            image: '/images/product-3.jpg',
            price: 132.5,
            brand: 'Adidas',
            rating: 4.1,
            numReviews: 35,
            countInStock: 3,
        },
        {
            _id: '444444444444444444444444',
            name: 'Converse Chuck Taylor All Star Lift Low Top Shoes',
            category: 'Shoes',
            image: '/images/product-4.webp',
            price: 61.6,
            brand: 'Converse',
            rating: 4.2,
            numReviews: 89,
            countInStock: 0,
        },
        {
            _id: '555555555555555555555555',
            name: 'Sneaker Rhyton Logo Leather',
            category: 'Shoes',
            image: '/images/product-5.jpg',
            price: 65,
            brand: 'Gucci',
            rating: 4.6,
            numReviews: 45,
            countInStock: 2,
        },
        {
            _id: '666666666666666666666666',
            name: 'Monk Strap Men\'s Dress Shoes',
            category: 'Shoes',
            image: '/images/product-6.jpeg',
            price: 47,
            brand: 'Monk Strap',
            rating: 3.9,
            numReviews: 38,
            countInStock: 10,
        },
    ]
}